name: configuration_delegate
version: 0.1.0
description: Configuration Delegate
homepage: https://github.com/blackpoint-dev/configuration_delegate

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  meta: ^1.2.4
  rxdart: ^0.26.0

dev_dependencies:
  analysis_options:
    git: https://github.com/vaetas/analysis_options.git
